//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MathDatas
    {
        public System.Guid MathId { get; set; }
        public System.DateTime DateTime { get; set; }
        public double PercentageWrong { get; set; }
        public double PercentageCorrect { get; set; }
        public int EquationsMade { get; set; }
        public Nullable<int> ClassGroup_Id { get; set; }
        public Nullable<System.Guid> User_UserId { get; set; }
    }
}
