//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MathGameScores
    {
        public int ScoreId { get; set; }
        public System.Guid StudentId { get; set; }
        public int TotalSum { get; set; }
        public int CorrectSums { get; set; }
        public int InCorrectSums { get; set; }
        public int FinalScore { get; set; }
        public System.DateTime SaveTime { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
