//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbi441943Entities1 : DbContext
    {
        public dbi441943Entities1()
            : base("name=dbi441943Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LanguageGameScores> LanguageGameScores { get; set; }
        public virtual DbSet<MathGameScores> MathGameScores { get; set; }
        public virtual DbSet<Schools> Schools { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<TypingGameScores> TypingGameScores { get; set; }
        public virtual DbSet<Words> Words { get; set; }
    }
}
